[package]
name = "fusen-net"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
#网络协议处理
tokio.workspace = true
bytes.workspace = true
futures.workspace = true