[package]
name = "fusen-net"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true


[dependencies]
#网络协议处理
tokio = { version = "1.44.2", features = ["sync", "io-util"] }
bytes = "1.10.1"
hyper-util = "0.1.11"
futures = "0.3.31"
s2n-quic = "1.57.0"
gm-quic = "0.2.1"
quinn = { version = "0.11.7", features = ["runtime-tokio"] }
rustls = "0.23.26"
rcgen = "0.13.2"

#日志处理
tracing = "0.1.41"
tracing-futures = { version = "0.2.5" }
tracing-subscriber = "0.3.19"
pretty_env_logger = "0.5.0"
chrono = "0.4.40"

#json序列化
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
pnet = "0.35.0"
uuid = { version = "1.16.0", features = ["v4"] }
thiserror = "2.0.12"
