[package]
name = "examples"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
tokio = { version = "1.44.2", features = ["rt-multi-thread"] }
tracing-subscriber = "0.3.19"
tracing = "0.1.41"

fusen-net = { path = "../fusen-net" }
